#!/usr/bin/env bash
bin_dir=`cd "$(dirname "$BASH_SOURCE[0]")"; pwd`
[ -f "$bin_dir/requirements.txt" ] \
	&& python3 -m venv env \
	&& source $bin_dir/env/bin/activate \
	&& python3 -m pip install --upgrade pip \
	&& pip3 install -r requirements.txt --quiet 
python3 $bin_dir/sync-aliases.py "$@"